cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from django.conf.urls import include, url
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_olmis import urls as olmis_urls
from django.contrib.auth.views import (
    password_reset_done, password_change, password_change_done)
from cpovc_auth.views import password_reset
from django.views.generic import TemplateView

from cpovc_access.forms import StrictPasswordChangeForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    url(r'^$', 'cpims.views.home', name='home'),
    url(r'^accounts/request/$', 'cpims.views.access', name='access'),
    url(r'^accounts/terms/(?P<id>\d+)/$', 'cpovc_access.views.terms',
        name='terms'),
    url(r'^login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^logout/$', 'cpovc_auth.views.log_out', name='logout'),
    url(r'^register/$', 'cpovc_auth.views.register', name='register'),
    url(r'^auth/', include(auth_urls)),
    url(r'^registry/', include(registry_urls)),
    url(r'^forms/', include(forms_urls)),
    url(r'^reports/', include(reports_urls)),
    url(r'^gis/', include(gis_urls)),
    url(r'^api/', include(api_urls)),
    url(r'^api_consumer/', include(olmis_urls)),
    url(r'^accounts/login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    url(r'^accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'cpovc_auth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^reset/$', 'cpovc_auth.views.reset', name='reset'),
    url(r'^accounts/password/change/$', password_change,
        {'post_change_redirect': '/accounts/password/change/done/',
         'template_name': 'registration/password_change.html',
         'password_change_form': StrictPasswordChangeForm},
        name='password_change'),
    url(r'^accounts/password/change/done/$', password_change_done,
        {'template_name': 'registration/password_change_done.html'}),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_auth/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin, Group, Permission)
from datetime import datetime


class CPOVCUserManager(BaseUserManager):

    def create_user(self, username, reg_person, password=None):

        from cpovc_registry.models import RegPerson
        if not username:
            raise ValueError('The given username must be set')

        now = datetime.now()
        user = self.model(username=username,
                          reg_person=RegPerson.objects.get(pk=int(reg_person)),
                          password=password,
                          is_staff=False,
                          is_active=True,
                          is_superuser=False,
                          role='Public',
                          timestamp_created=now,
                          timestamp_updated=now,
                          )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, reg_person, password=None):
        user = self.create_user(username=username,
                                reg_person=reg_person,
                                password=password
                                )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class AppUser(AbstractBaseUser, PermissionsMixin):
    reg_person = models.OneToOneField('cpovc_registry.RegPerson', null=False)
    role = models.CharField(max_length=20, unique=False, default='Public')
    username = models.CharField(max_length=20, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)
    password_changed_timestamp = models.DateTimeField(null=True)

    # For admin so remove if you don't want to use admin
    first_name = False
    last_name = False
    date_joined = False

    objects = CPOVCUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['reg_person']

    def _get_email(self):
        return self.reg_person.email

    email = property(_get_email)

    def _get_first_name(self):
        return self.reg_person.first_name

    first_name = property(_get_first_name)

    def _get_surname(self):
        return self.reg_person.surname

    surname = property(_get_surname)

    def _get_last_name(self):
        return self.reg_person.other_names

    last_name = property(_get_last_name)

    def get_full_name(self):
        """
        TO DO - Get this from persons table but for now just use
        Workforce ID
        """
        return self.username

    def get_short_name(self):
        """
        Return Workforce ID if exists or not
        """
        return self.username

    def get_username(self):
        """
        Return National ID if exists else Workforce ID
        """
        if self.username:
            return self.username
        else:
            return None

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'auth_user'


class CPOVCPermission(Permission):
    permission_description = models.CharField(max_length=255)
    permission_set = models.CharField(max_length=100)
    permission_type = models.CharField(max_length=50, blank=True)
    restricted_to_self = models.BooleanField(blank=True, default=False)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    timestamp_modified = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'auth_permission_detail'


class CPOVCRole(Group):
    group_id = models.CharField(max_length=5)
    group_name = models.CharField(max_length=100)
    group_description = models.CharField(max_length=255)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    automatic = models.BooleanField(default=False)
    timestamp_modified = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'auth_group_detail'


class CPOVCUserRoleGeoOrg(models.Model):
    # Put here to avoid cyclic imports because of User model
    # from cpovc_registry.models import RegPersonsGeo, RegOrgUnit
    user = models.ForeignKey(AppUser)
    group = models.ForeignKey(CPOVCRole)
    org_unit = models.ForeignKey('cpovc_registry.RegOrgUnit', null=True)
    area = models.ForeignKey('cpovc_main.SetupGeography', null=True)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        db_table = 'auth_user_groups_geo_org'

templates/reports/case_load.html
{% extends 'base.html' %}
{% block page_title %} {{block.super}} Case load reports {% endblock page_title%}

{% load staticfiles %}

{% block style_code%}

{% endblock style_code%}


{% block javascript_code%}

{% endblock javascript_code%}

{% block primary%}
<h1 class="page-header">Case Load Report</h1>

{% if messages %}
<div id="messages" class="alert alert-danger fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.error %} class="{{ message.danger }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>                        
                <h4 class="panel-title">Report details and parameters</h4>
            </div>
            <div class="panel-body">
                <form class="form-horizontal form-bordered" action="{% url 'caseload_reports' %}" method="POST" data-parsley-validate="true" id="case_load_report">
                   {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4">Report Region :</label>
                        <div class="col-md-6 col-sm-6">
                            <label><input data-parsley-required="true" data-parsley-errors-container="#type_error" id="report_type_0" name="report_region" class="report_region" type="radio" value="1" checked="checked" /> National</label>
                            <label><input data-parsley-required="true" data-parsley-errors-container="#type_error" id="report_type_1" name="report_region" class="report_region" type="radio" value="2" /> County</label>
                            <label><input data-parsley-required="true" data-parsley-errors-container="#type_error" id="report_type_2" name="report_region" class="report_region" type="radio" value="3" /> Sub-county</label>
                            <label><input data-parsley-required="true" data-parsley-errors-container="#type_error" id="report_type_3" name="report_region" class="report_region" type="radio" value="4" /> Organisation Unit</label>
                            <div id="type_error"></div>
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select report type."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
                    <div class="form-group" id="report_county">
                        <label class="control-label col-md-4 col-sm-4">County :</label>
                        <div class="col-md-6 col-sm-6">
                            {{ form.county }}
                            <div id="county_error"></div>
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select one county."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
                    <div class="form-group" id="report_sub_county">
                        <label class="control-label col-md-4 col-sm-4">Sub-county :</label>
                        <div class="col-md-6 col-sm-6">
                            {{ form.sub_county }}
                            <div id="sub_county_error"></div>
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select one sub-county."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
                    <div class="form-group" id="report_reg_unit">
                        <label class="control-label col-md-4 col-sm-4">Organisation Unit :</label>
                        <div class="col-md-6 col-sm-6">
                            {{ form.org_unit }}
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select Organisation Unit."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4">Reporting period :</label>
                        <div class="col-md-2 col-sm-2">
                            {{ form.report_type }}
                        </div>
                        <div class="col-md-2 col-sm-2">
                        {{ form.report_period }}
                        </div>
                        <div class="col-md-2 col-sm-2">
                        {{ form.report_year }}
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select report type."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
				
                    <div class="panel-body panel-form">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-4"></label>
                            <div class="col-md-6 col-sm-6">
                                <button type="submit" class="btn btn-sm btn-primary m-r-5"><i class="fa fa-check-square-o"></i> View </button>
                            </div>
                        </div>
                    </div>
				</form>
			</div>
        </div>
        <!-- end panel -->
        <center><div id="report_results"></div></center>
        <br/>
        <div id="report_html"></div>
        
    </div>
    <!-- end col-12 -->       
</div>
<!-- end row -->

{% endblock primary%}

{% block lazy_javascript_code %}
<script type="text/javascript" src="{% static 'js/bootstrap-multiselect.js' %}"></script>
<script>
jQuery(document).ready(function() {
    $('#sub_county, #county').multiselect({
        selectAllValue: 'multiselect-all',
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true,
        numberDisplayed: 1,
        maxHeight: 300,
        buttonWidth: '100%',
        disableIfEmpty: true,
        enableClickableOptGroups: true,
        nonSelectedText: 'Please select sub-county',
        buttonClass: 'btn btn-white'
    });
    $('#case_load_report').on('submit', function(event){
        event.preventDefault();
        $('#report_results').html("Processing Report...");
        $('#report_html').empty();
        var oname = $("#id_org_unit option:selected").text();
        $.ajax({
            url : "{% url 'caseload_reports' %}",
            type : "POST",
            dataType: "json",
            data: $("#case_load_report").serialize() + "&org_unit_name="+oname,
            // handle a successful response
            success : function(response) {
                var file_name = response.file_name;
                var status = response.status;
                var message = response.message;
                var url = '<a href="{% url "download_reports" file_name="0000" %}">';
                // PDF
                var pdf = url.replace('0000', file_name+'.pdf');
                pdf += '<button type="button" class="btn btn-danger m-r-5 m-b-5">';
                pdf += '<i class="fa fa-file-pdf-o"></i> PDF</button></a>';
                // Excel
                var xlsx = url.replace('0000', file_name+'.xlsx');
                xlsx += '<button type="button" class="btn btn-success m-r-5 m-b-5">';
                xlsx += '<i class="fa fa-file-excel-o"></i> Excel</button></a>';
                var prnt = '<button type="button" class="btn btn-success m-r-5 m-b-5" onclick="PrintElem(\'#report_html\')"><i class="fa fa-file-excel-o"></i> Print report</button>';
                if (status == 0){
                    $('#report_results').html(prnt + xlsx);//pdf + xlsx
                }else{
                    $('#report_results').html(message);                
                }
                $('#report_html').html(response.report);  
            },
            // handle a non-successful response
            error : function(xhr, errmsg, err) {
                $('#report_results').html("Oops! We have encountered an error: " + errmsg);
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });
    });
    // Hide some stuff by default
    $("#report_type_0").prop("checked", true);
    $('#report_county').hide();
    $('#county').attr('data-parsley-required', 'false');
    $('#report_sub_county').hide();
    $('#sub_county').attr('data-parsley-required', 'false');
    $('#report_reg_unit').hide();

    
    $(".report_region").click(function(e) {
        var res = $('input[name=report_region]:checked', '#case_load_report').val();
        if (res == '1'){
            $('#report_reg_unit').hide();
            $('#id_org_unit').attr('data-parsley-required', 'false');
            $('#id_org_unit').val('');
            $('#report_county').hide();
            $('#county').attr('data-parsley-required', 'false');

            $('#report_sub_county').hide();
            $('#sub_county').attr('data-parsley-required', 'false');
        }else if (res == '2'){
            $('#report_reg_unit').hide();
            $('#id_org_unit').attr('data-parsley-required', 'false');
            $('#id_org_unit').val('');
            $('#report_county').show();
            $('#county').attr('data-parsley-required', 'true');
            $('#county').val('');
            $('#county').multiselect('rebuild');

            $('#report_sub_county').hide();
            $('#sub_county').attr('data-parsley-required', 'false');
        }else if (res == '3'){
            $('#report_reg_unit').hide();
            $('#id_org_unit').attr('data-parsley-required', 'false');
            $('#id_org_unit').val('');
            $('#report_county').show();
            $('#county').attr('data-parsley-required', 'true');
            $('#county').val('');
            $('#county').multiselect('rebuild');

            $('#report_sub_county').show();
            $('#sub_county').attr('data-parsley-required', 'true');
            $('#sub_county').empty();
            $('#sub_county').multiselect('rebuild');
        }else if (res == '4'){
            $('#report_reg_unit').show();
            $('#id_org_unit').attr('data-parsley-required', 'true');

            $('#report_county').hide();
            $('#county').attr('data-parsley-required', 'false');

            $('#report_sub_county').hide();
            $('#sub_county').attr('data-parsley-required', 'false');
        }
    });

    // Cascading drop down
    $("#county").change(function(e) {
        var county = $("#county").val();
        var csrftoken = $.cookie('csrftoken');
        var values = {'sub_county': 0,
                      'county': county, 'action': 6,
                      'csrfmiddlewaretoken': csrftoken };
        $('#sub_county').empty();
        $.ajax({
            type: "POST",
            data: values,
            dataType: "json",
            url: "{% url 'reg_lookup' %}",
            success: function(data){
                var wards = data.wards;
                $('#sub_county').html("<option value=''>Please Select</option>");           
                $.each(wards, function(i, record) {
                    var ward_attribs = wards[i].split(",");
                    $('#sub_county')
                        .append($("<option></option>")
                        .attr("value", ward_attribs[0])
                        .text(ward_attribs[1]));
                 });
                 $('#sub_county').multiselect('rebuild');
            },
            error: function(){
                $('#messages').html("Error")
            }
        });
    });

    M = new Array('January','February','March','April','May','June',
                  'July','August','September','October','November','December');
    Q = new Array('Qtr1','Qtr2','Qtr3','Qtr4');
    Y = new Array('Financial');

    populateSelect();

    $(function() {
        $('#id_report_type').change(function(){
            populateSelect();
        });
    });


    function populateSelect(){
        cat = $('#id_report_type').val();
        $('#id_report_period').html('');

        if (cat != ''){
            eval(cat).forEach(function(t) { 
                $('#id_report_period').append('<option>'+t+'</option>');
            });
        }else{
             $('#id_report_period').append('<option></option>'); 
        }
    }

});
function PrintElem(elem)
    {
        Popup($(elem).html());
    }

    function Popup(data) 
    {
        var lscape = '<style type="text/css" media="print">@page { size: landscape; }</style>';
        var bstrap = '<link href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" />';
        var mywindow = window.open('', 'report_html', 'height=400,width=600');
        mywindow.document.write('<html><head><title>Case Load Report</title>');
        mywindow.document.write(bstrap);
        mywindow.document.write('<link href="{% static "css/style.css" %}" rel="stylesheet" />');
        mywindow.document.write(lscape);
        mywindow.document.write('</head><body >');
        mywindow.document.write(data);
        mywindow.document.write('</body></html>');
        // IE Handlers
        mywindow.document.close(); // necessary for IE >= 10
        mywindow.focus(); // necessary for IE >= 10
        // Other browsers handlers
        mywindow.print();
        mywindow.close();

        return true;
    }
</script>
{% endblock lazy_javascript_code %}

templates/reports/reports_documents.html
{% extends 'base.html' %}
{% block page_title %} {{block.super}}Reports{% endblock page_title%}

{% load staticfiles %}

{% block primary%}
<h1 class="page-header">Reports <small>Document templates</small></h1>

{% if messages %}
<div id="messages" class="alert alert-danger fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.error %} class="{{ message.danger }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>                        
                <h4 class="panel-title">Report / document details</h4>
            </div>
            <div class="panel-body">
				<form id="reports" class="form-horizontal form-bordered" action="{% url 'reports' %}" method="POST" data-parsley-validate="true">
                   {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4">Organisation Unit :</label>
                        <div class="col-md-6 col-sm-6">
                            {{ form.org_unit }}
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select at least one sub-county."><i class="fa fa-info-circle fa-lg"></i></a>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4 col-sm-4">Report / document type :</label>
                        <div class="col-md-6 col-sm-6">
	                        {{ form.document_type }}
                        </div>
                        <a href="#" data-toggle="tooltip" title="Select report type."><i class="fa fa-info-circle fa-lg"></i></a>
					</div>
					<div class="form-group">
                        <label class="control-label col-md-4 col-sm-4">Child :</label>
                        <div class="col-md-6 col-sm-6">
	                        {{ form.child }} {{ form.cpims_child }}
	                        <div id="case_details"></div>
                        </div>
                        <a href="#" data-toggle="tooltip" title="Start typing name of child."><i class="fa fa-info-circle fa-lg"></i></a>
					</div>
					<div class="form-group" id="case_more">
                        <label class="control-label col-md-4 col-sm-4">Case details : </label>
                        <div class="col-md-6 col-sm-6" id="case_data">
                        </div>
					</div>
				
                    <div class="panel-body panel-form" id="case_proceed">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-4"></label>
                            <div class="col-md-6 col-sm-6">
                                <button type="submit" class="btn btn-sm btn-primary m-r-5"><i class="fa fa-check-square-o"></i> Generate</button>
                            </div>
                        </div>
                    </div>
				</form>
			</div>
        </div>
        <!-- end panel -->
        <div id="report_results"></div>
	    {% if results|length %}
	    	<div class="table-responsive">
				<button type="button" class="btn btn-info m-r-5 m-b-5"> <i class="fa fa-folder-open-o"></i> Preview</button>
				<a href="{% url 'download_reports' file_name=file_name %}.xls">
					<button type="button" class="btn btn-success m-r-5 m-b-5">
					<i class="fa fa-file-excel-o"></i> Excel</button>
				</a>
				<a href="{% url 'download_reports' file_name=file_name %}.pdf">
					<button type="button" class="btn btn-danger m-r-5 m-b-5"> 
					<i class="fa fa-file-pdf-o"></i> PDF</button>
				</a>
				<a href="{% url 'download_reports' file_name=file_name %}.csv">
					<button type="button" class="btn btn-warning m-r-5 m-b-5">
					<i class="fa fa-file-text-o"></i> CSV</button>
				</a>
	        </div>
	    {% endif %}
    </div>
    <!-- end col-12 -->       
</div>
<!-- end row -->

{% endblock primary%}

{% block lazy_javascript_code %}
<script>
jQuery(document).ready(function() {
    $('#reports').on('submit', function(event){
	    event.preventDefault();
	    var report_id = $('#id_document_type').val();
	    var report_name = $('#id_document_type option:selected').text();
	    var org_unit = $('#id_org_unit').val();
	    var child_id = $('#cpims_child_id').val();
	    var csrftoken = $.cookie('csrftoken');
        var values = {'id' : report_id, 'name': report_name,
                      'org_unit': org_unit,
                      'child_id': child_id,
                      'csrfmiddlewaretoken': csrftoken };
        $('#report_results').html("Processing Report...");
	    $.ajax({
	        url : "{% url 'reports' %}",
	        type : "POST",
	        data : values,
	        // handle a successful response
	        success : function(json) {
	        	var file_name = json.file_name;
	        	var url = '<a href="{% url "download_reports" file_name="0000" %}.pdf">';
	        	var data = url.replace('0000', file_name);
				data += '<button type="button" class="btn btn-danger m-r-5 m-b-5">';
				data += '<i class="fa fa-file-pdf-o"></i> PDF</button></a>';
	            $('#report_results').html(data);
	            console.log(json);
	        },
	        // handle a non-successful response
	        error : function(xhr, errmsg, err) {
	            $('#report_results').html("Oops! We have encountered an error: " + errmsg);
	            console.log(xhr.status + ": " + xhr.responseText);
	        }
	    });

	});
	$('#child_id').val('');
	$('#cpims_child_id').val('');
	$('#case_more').hide();
	$('#case_proceed').hide();
	// To get Children
    $( "#child_id" ).autocomplete({
        source: function( request, response ) {
        $.ajax({
          url: "{% url 'registry' %}",
          dataType: "json",
          data: {q: request.term, id: 1},
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 4,
      appendTo: "#case_details",
      select: function( event, ui ) {
      	$('#case_more').show();
	    $('#case_proceed').show();
	    var dt = '<input type="radio" name="case" value="1"> 0999/0009/2001 | 01-Mar-2015<br>';
	    $('#case_data').html(dt);
        // $('#log_cg').empty();
        $('#cpims_child_id').val(ui.item.id);
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
    });
});
</script>
{% endblock lazy_javascript_code %}